on: [push]
name: Release Build
jobs:
  build:
    name: Cargo build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build Release Mode
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --verbose
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: eldenring-alt-saves
          path: target/release/eldenring_alt_saves.dll